import 'package:appclient/models/productFvoriteModel.dart';

class Autogenerated {
  String? message;
  List<ListCart>? listCart;

  Autogenerated({this.message, this.listCart});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    if (json['listCart'] != null) {
      listCart = <ListCart>[];
      json['listCart'].forEach((v) {
        listCart!.add(new ListCart.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    if (this.listCart != null) {
      data['listCart'] = this.listCart!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ListCart {
  String? sId;
  UserId? userId;
  ProductId? productId;
  int? quantity;
  String? status;
  String? createdAt;
  String? updatedAt;
  int? iV;

  ListCart(
      {this.sId,
      this.userId,
      this.productId,
      this.quantity,
      this.status,
      this.createdAt,
      this.updatedAt,
      this.iV});

  ListCart.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    userId =
        json['user_id'] != null ? new UserId.fromJson(json['user_id']) : null;
    productId = json['product_id'] != null
        ? new ProductId.fromJson(json['product_id'])
        : null;
    quantity = json['quantity'];
    status = json['status'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['user_id'] = this.userId;
    if (this.userId != null) {
      data['user_id'] = this.userId!.toJson();
    }
    if (this.productId != null) {
      data['product_id'] = this.productId!.toJson();
    }
    data['quantity'] = this.quantity;
    data['status'] = this.status;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['__v'] = this.iV;
    return data;
  }
}


class ProductId {
  String? sId;
  Product? product;
  SizeId? sizeId;
  SizeId? colorId;
  int? quantity;
  String? createdAt;
  String? updatedAt;
  int? iV;

  ProductId(
      {this.sId,
      this.product,
      this.sizeId,
      this.colorId,
      this.quantity,
      this.createdAt,
      this.updatedAt,
      this.iV});

  ProductId.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    product = json['product_id'] != null
        ? new Product.fromJson(json['product_id'])
        : null;
    sizeId =
        json['size_id'] != null ? new SizeId.fromJson(json['size_id']) : null;
    colorId =
        json['color_id'] != null ? new SizeId.fromJson(json['color_id']) : null;
    quantity = json['quantity'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    if (this.product != null) {
      data['product_id'] = this.product!.toJson();
    }
    if (this.sizeId != null) {
      data['size_id'] = this.sizeId!.toJson();
    }
    if (this.colorId != null) {
      data['color_id'] = this.colorId!.toJson();
    }
    data['quantity'] = this.quantity;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['__v'] = this.iV;
    return data;
  }
}

class Product {
  String? sId;
  String? name;
  List<String>? image;
  int? price;

  Product({this.sId, this.name, this.image, this.price});

  Product.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    name = json['name'];
    image = json['image'].cast<String>();
    price = json['price'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['name'] = this.name;
    data['image'] = this.image;
    data['price'] = this.price;
    return data;
  }
}

class SizeId {
  String? sId;
  String? name;

  SizeId({this.sId, this.name});

  SizeId.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['name'] = this.name;
    return data;
  }
}
