class Autogenerated {
  int? status;
  String? msg;
  List<Data>? data;

  Autogenerated({this.status, this.msg, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    msg = json['msg'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['msg'] = this.msg;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String? sId;
  UserId? userId;
  CartId? cartId;
  int? payments;
  int? totalAmount;
  int? status;
  String? date;
  int? iV;

  Data(
      {this.sId,
      this.userId,
      this.cartId,
      this.payments,
      this.totalAmount,
      this.status,
      this.date,
      this.iV});

  Data.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    userId =
        json['user_id'] != null ? new UserId.fromJson(json['user_id']) : null;
    cartId =
        json['cart_id'] != null ? new CartId.fromJson(json['cart_id']) : null;
    payments = json['payments'];
    totalAmount = json['total_amount'];
    status = json['status'];
    date = json['date'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    if (this.userId != null) {
      data['user_id'] = this.userId!.toJson();
    }
    if (this.cartId != null) {
      data['cart_id'] = this.cartId!.toJson();
    }
    data['payments'] = this.payments;
    data['total_amount'] = this.totalAmount;
    data['status'] = this.status;
    data['date'] = this.date;
    data['__v'] = this.iV;
    return data;
  }
}

class UserId {
  String? sId;
  String? username;
  String? password;
  String? email;
  String? fullName;
  String? phoneNumber;
  String? role;
  bool? status;
  String? address;
  String? avata;
  String? token;
  String? deviceId;

  UserId(
      {this.sId,
      this.username,
      this.password,
      this.email,
      this.fullName,
      this.phoneNumber,
      this.role,
      this.status,
      this.address,
      this.avata,
      this.token,
      this.deviceId});

  UserId.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    username = json['username'];
    password = json['password'];
    email = json['email'];
    fullName = json['full_name'];
    phoneNumber = json['phone_number'];
    role = json['role'];
    status = json['status'];
    address = json['address'];
    avata = json['avata'];
    token = json['token'];
    deviceId = json['deviceId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['username'] = this.username;
    data['password'] = this.password;
    data['email'] = this.email;
    data['full_name'] = this.fullName;
    data['phone_number'] = this.phoneNumber;
    data['role'] = this.role;
    data['status'] = this.status;
    data['address'] = this.address;
    data['avata'] = this.avata;
    data['token'] = this.token;
    data['deviceId'] = this.deviceId;
    return data;
  }
}

class CartId {
  String? sId;
  String? userId;
  ProductId? productId;
  int? quantity;
  String? status;
  String? createdAt;
  String? updatedAt;
  int? iV;

  CartId(
      {this.sId,
      this.userId,
      this.productId,
      this.quantity,
      this.status,
      this.createdAt,
      this.updatedAt,
      this.iV});

  CartId.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    userId = json['user_id'];
    productId = json['product_id'] != null
        ? new ProductId.fromJson(json['product_id'])
        : null;
    quantity = json['quantity'];
    status = json['status'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['user_id'] = this.userId;
    if (this.productId != null) {
      data['product_id'] = this.productId!.toJson();
    }
    data['quantity'] = this.quantity;
    data['status'] = this.status;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['__v'] = this.iV;
    return data;
  }
}

class ProductId {
  String? sId;
  product? productId;
  SizeId? sizeId;
  ColorId? colorId;
  int? quantity;
  String? createdAt;
  String? updatedAt;
  int? iV;

  ProductId(
      {this.sId,
      this.productId,
      this.sizeId,
      this.colorId,
      this.quantity,
      this.createdAt,
      this.updatedAt,
      this.iV});

  ProductId.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    productId = json['product_id'] != null
        ? new product.fromJson(json['product_id'])
        : null;
    sizeId =
        json['size_id'] != null ? new SizeId.fromJson(json['size_id']) : null;
    colorId = json['color_id'] != null
        ? new ColorId.fromJson(json['color_id'])
        : null;
    quantity = json['quantity'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    if (this.productId != null) {
      data['product_id'] = this.productId!.toJson();
    }
    if (this.sizeId != null) {
      data['size_id'] = this.sizeId!.toJson();
    }
    if (this.colorId != null) {
      data['color_id'] = this.colorId!.toJson();
    }
    data['quantity'] = this.quantity;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['__v'] = this.iV;
    return data;
  }
}

class product {
  String? sId;
  String? name;
  String? description;
  List<String>? image;
  String? categoryId;
  int? price;
  String? createdAt;
  int? iV;

  product(
      {this.sId,
      this.name,
      this.description,
      this.image,
      this.categoryId,
      this.price,
      this.createdAt,
      this.iV});

  product.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    name = json['name'];
    description = json['description'];
    image = json['image'].cast<String>();
    categoryId = json['category_id'];
    price = json['price'];
    createdAt = json['createdAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['name'] = this.name;
    data['description'] = this.description;
    data['image'] = this.image;
    data['category_id'] = this.categoryId;
    data['price'] = this.price;
    data['createdAt'] = this.createdAt;
    data['__v'] = this.iV;
    return data;
  }
}

class SizeId {
  String? sId;
  String? name;
  int? iV;

  SizeId({this.sId, this.name, this.iV});

  SizeId.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    name = json['name'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['name'] = this.name;
    data['__v'] = this.iV;
    return data;
  }
}

class ColorId {
  String? sId;
  String? name;
  String? colorcode;
  int? iV;

  ColorId({this.sId, this.name, this.colorcode, this.iV});

  ColorId.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    name = json['name'];
    colorcode = json['colorcode'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['name'] = this.name;
    data['colorcode'] = this.colorcode;
    data['__v'] = this.iV;
    return data;
  }
}